### for dataset params.
input_dir: /HDD/datasets/public/camvid
dataset_format: mask

### for model params.
model_name: fcn_resnet101
input_height: 4
input_width: 4
input_channel: 3
weights: null #the weights enum name to load
weights_backbone: null #the backbone weights enum name to load

### for loss params.
aux_loss: false

### for training params.
device: cuda
start_epoch: 0
epochs: 30
batch_size: 1
workers: 16
init_lr: 0.01
momentum: 0.9
weight_decay: 0.0001
lr_warmup_epochs: 0
lr_warmup_method: linear
lr_warmup_decay: 0.01
# Mixed precision training parameters
amp: false 

### for logging
output_dir: './res'
print_freq: 10

### for distributed training params.
world_size: 1 #number of distributed processes
dist_url: env:// #url used to set up distributed training

### etc.
resume: false # str >> seed_model

#Forces the use of deterministic algorithms only ?????????????????????
use_deterministic_algorithms: false
test_only: false
